"""
Django settings for catalog project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
from pathlib import Path
from os import getenv
from logging import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

SECRET_KEY = getenv("SECRET_KEY", "oi")
ENV = getenv("ENV", "development")

DEBUG = True
ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'corsheaders',
    'products'
]

REST_FRAMEWORK = { 
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_PARSER_CLASSES': [
       'rest_framework.parsers.FormParser',
       'rest_framework.parsers.MultiPartParser',
       'rest_framework.parsers.JSONParser',
    ]
}


# SWAGGER_SETTINGS = {
#     "VALIDATOR_URL": [""],
#     'JSON_EDITOR': True,
#     "exclude_url_names": ['docs', ],
#     "exclude_namespaces": [],
#     "api_version": '0.1',
#     "SUPPORTED_SUBMIT_METHODS": [
#         'get',
#         'post',
#         'put',
#         'delete'
#     ],
#     'USE_SESSION_AUTH': False,
#     'SECURITY_DEFINITIONS': {
#         'oauth2': {
#             'type': 'apiKey',
#             'description': 'Personal API Key authorization',
#             'name': 'Authorization',
#             'in': 'header',
#         }
#     },
#     'APIS_SORTER': 'alpha',
#     "SHOW_REQUEST_HEADERS": True,
#     "VALIDATOR_URL": False,
#     "api_key": 'veristoken fbe16f3a4c292c774c54', # An API key
#     'REFETCH_SCHEMA_ON_LOGOUT': True,
#     'info': {
#         'contact': 'apiteam@wordnik.com',
#         'description': 'This is a sample server Petstore server. '
#                         'You can find out more about Swagger at '
#                         '<a href="http://swagger.wordnik.com">'
#                         'http://swagger.wordnik.com</a> '
#                         'or on irc.freenode.net, #swagger. '
#                         'For this sample, you can use the api key '
#                         '"special-key" to test '
#                         'the authorization filters',
#         'license': 'Apache 2.0',
#         'licenseUrl': 'http://www.apache.org/licenses/LICENSE-2.0.html',
#         'termsOfServiceUrl': 'http://helloreverb.com/terms/',
#         'title': 'Products Catalog API',
#     },
# }

# SWAGGER_SETTINGS = {
#     'exclude_url_names': ['docs'],
#     'exclude_namespaces': [],
#     'api_version': '0.1',
#     'api_path': '/',
#     'relative_paths': False,
#     'enabled_methods': [
#         'get',
#         'post',
#         'put',
#         'patch',
#         'delete'
#     ],
#     'api_key': 'test',
#     'is_authenticated': False,
#     'is_superuser': False,
#     'unauthenticated_user': 'django.contrib.auth.models.AnonymousUser',
#     'permission_denied_handler': None,
#     'resource_access_handler': None,
#     # 'base_path':'helloreverb.com/docs',
#     'info': {
#         'contact': 'apiteam@wordnik.com',
#         'description': 'This is a sample server Petstore server. '
#                        'You can find out more about Swagger at '
#                        '<a href="http://swagger.wordnik.com">'
#                        'http://swagger.wordnik.com</a> '
#                        'or on irc.freenode.net, #swagger. '
#                        'For this sample, you can use the api key '
#                        '"special-key" to test '
#                        'the authorization filters',
#         'license': 'Apache 2.0',
#         'licenseUrl': 'http://www.apache.org/licenses/LICENSE-2.0.html',
#         'termsOfServiceUrl': 'http://helloreverb.com/terms/',
#         'title': 'Swagger Sample App',
#     },
#     'doc_expansion': 'none',
# }
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': getenv('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}
config.dictConfig(LOGGING)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'catalog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries' : {
                'staticfiles': 'django.templatetags.static', 
            }
        },
    },
]

WSGI_APPLICATION = 'catalog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'admin',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'db',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

CORS_ORIGIN_ALLOW_ALL = True
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if ENV == 'production':
    DEBUG = False
    SECRET_KEY = getenv('SECRET_KEY')
    SESSION_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_REDIRECT_EXEMPT = []
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')